### ISSUE TITLE
Text area color is transparent - not legible

### ISSUE THREAD

**Issue by Marigameo** [tcp19/tcp-grand-resume#31]
Set the color to black just like the input field

**Fix:** add the color prop to text-area component
<img width="1077" alt="Screenshot 2021-10-18 at 8 10 43 PM" src="https://user-images.githubusercontent.com/29794747/137753369-94abd84a-ec74-423f-8900-933f030d1fa2.png">

**Comment by Mr-emeka** [comment]
@Marigameo thanks for this, could you add the checkbox to it, it's almost invisible.

![image](https://user-images.githubusercontent.com/30534680/138496017-cce5d98c-057a-48e0-b68f-40c83eb6b91b.png)

**Comment by sandeep-v1404** [comment]
@Mr-emeka Can I work on this issue?

**Comment by Marigameo** [comment]
Done #45 

Sorry, I couldn't push to the same PR as I happened to clone repo fresh in my new device.
